# Generated by Django 6.0.1 on 2026-01-11 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6be8e28a-362b-45db-a759-056d88513d46"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
