# Generated by Django 6.0.1 on 2026-01-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_refreshtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
