# Generated by Django 6.0.1 on 2026-01-11 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_refreshtoken_revoked_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        db_column="owner_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                (
                    "folder",
                    models.ForeignKey(
                        db_column="folder_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.folder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("upload", models.BooleanField(default=False)),
                ("delete", models.BooleanField(default=False)),
                (
                    "folder",
                    models.ForeignKey(
                        db_column="folder_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="core.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
