# Generated by Django 6.0.1 on 2026-01-12 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_folder_file_folderpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folderpermission",
            name="folder",
            field=models.ForeignKey(
                db_column="folder_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_pormissions",
                to="core.folder",
            ),
        ),
        migrations.AlterField(
            model_name="folderpermission",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_permissions",
                to="core.user",
            ),
        ),
    ]
