# Generated by Django 6.0.1 on 2026-01-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_folderpermission_folder_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="folderpermission",
            old_name="delete",
            new_name="can_delete",
        ),
        migrations.RenameField(
            model_name="folderpermission",
            old_name="read",
            new_name="can_read",
        ),
        migrations.RenameField(
            model_name="folderpermission",
            old_name="upload",
            new_name="can_upload",
        ),
    ]
