# Generated by Django 6.0.1 on 2026-01-12 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_delete_folderpermission_can_delete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folderpermission",
            name="folder",
            field=models.ForeignKey(
                db_column="folder_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_permissions",
                to="core.folder",
            ),
        ),
    ]
